config/routes.rb
Rails.application.routes.draw do
  scope "(:mobile)", mobile: /m/ do
    namespace :admin do
      resources :articles
      resources :article_categories
      resources :categories do
        collection do
          post :add_child
          post :recompute_bar
          post :recompute_team_bar
        end
      end

      resources :events do
        collection do
          get  :add_children
          get  :set_parent
          post :upload_schedule
        end
        member do
          get     :create_from_children
          delete  :destroy_races
          patch   :update_attribute
          post    :upload
        end
        resources :races do
          collection do
            post :propagate
          end
        end
        resource :races_collection
      end

      resources :first_aid_providers
      resources :mailing_lists do
        resources :posts do
          collection do
            post :receive
          end
        end
      end
      resources :multi_day_events
      resources :pages do
        member do
          patch :update_attribute
        end
      end
      namespace :pages do
        resources :versions do
          member do
            get :revert
          end
        end
      end
      resources :people do
        resources :aliases
        collection do
          get  :cards
          get  :duplicates
          post :import
          get  :no_cards
          post :number_year_changed
          post :preview_import
          post :resolve_duplicates
        end
        member do
          get    :card
          post   :toggle_member
        end
        resources :race_numbers
        resources :results do
          post :move
        end
        resources :scores
      end
      post "/people/:id/merge/:other_person_id" => "people#merge", constraints: { id: /\d+/, other_person_id: /\d+/ }, as: :merge_person

      resources :races do
        member do
          patch :update_attribute
        end
        resources :results
      end

      resources :race_numbers

      resources :results do
        collection do
          post :find_person
          post :results
        end
        member do
          patch :update_attribute
        end
        resources :races
      end

      resources :series
      resources :single_day_events

      resources :teams do
        resources :aliases
        member do
          post  :cancel_in_place_edit
          post  :destroy_name
          post  :toggle_member
          patch :update_attribute
        end
      end
      post "/teams/:id/merge/:other_team_id" => "teams#merge", constraints: { id: /\d+/, other_team_id: /\d+/ }, as: :merge_team

      resources :velodromes do
        member do
          patch :update_attribute
        end
      end
      resources :weekly_series
    end

    resources :articles
    resources :article_categories
    resources :categories do
      resources :races
    end

    get ':controller/:id/aliases/:alias_id/destroy' => :destroy_alias, constraints: { id: /\d+/ }

    get '/admin/results/:id/scores' => 'admin/results#scores'
    get '/admin/racers' => 'admin/racers#index'
    patch '/admin/persons/update_attribute/:id' => 'admin/people#update_attribute'
    get '/admin' => 'admin/home#index', as: :admin_home

    get '/bar' => 'competitions/bar#index', as: "bar_root"
    get "/bar/:year/:discipline/:category" => "competitions/bar#show", as: "bar_full"
    get "/bar(/:year(/:discipline(/:category)))" => "competitions/bar#show", as: "bar", defaults: { discipline: "overall", category: "senior_men" }

    get '/cat4_womens_race_series/:year' => 'competitions/competitions#show', as: :cat4_womens_race_series, type: 'cat4_womens_race_series', constraints: { year: /\d{4}/ }
    get '/cat4_womens_race_series' => 'competitions/competitions#show', type: 'cat4_womens_race_series'

    resources :duplicate_people

    get '/events/:event_id/results' => 'results#event'
    get '/events/:event_id/people/:person_id/results' => 'results#person_event'
    get '/events/:event_id/teams/:team_id/results' => 'results#team_event'
    get '/events/:event_id/teams/:team_id/results/:race_id' => 'results#team_event'
    get '/events/:event_id' => 'results#event'

    resources :event_teams do
      resources :event_team_memberships
    end

    resources :events do
      resources :event_team_memberships
      resources :event_teams
      resources :results
      resources :people do
        resources :results
        resources :event_team_memberships
      end
      resources :races
      resources :teams do
        resources :results
      end
    end

    resources :event_team_memberships

    get "/human_dates/:date" => "human_dates#show", constraints: { date: /.*/ }

    resources :photos

    resources :races
    get '/rider_rankings/:year' => 'competitions/competitions#show', as: :rider_rankings, type: 'rider_rankings', constraints: { year: /\d{4}/ }
    get '/rider_rankings' => 'competitions/competitions#show', as: :rider_rankings_root, type: 'rider_rankings'
    get '/ironman(/:year)' => 'competitions/ironman#index', as: :ironman
    get '/oregon_cup/rules' => 'competitions/oregon_cup#rules'
    get '/oregon_cup/races' => 'competitions/oregon_cup#races'
    get '/oregon_cup/:year' => 'competitions/oregon_cup#index', as: :oregon_cup
    get '/oregon_cup' => 'competitions/oregon_cup#index', as: :oregon_cup_root
    get "/oregon_tt_cup/:year" => "competitions/competitions#show", type: "oregon_tt_cup"
    get "/oregon_tt_cup" => "competitions/competitions#show", type: "oregon_tt_cup"
    get '/oregon_womens_prestige_series' => "competitions/competitions#show", type: "oregon_womens_prestige_series"
    get '/owps' => "competitions/competitions#show", type: "oregon_womens_prestige_series"
    get "/:slug/join" => "event_team_memberships#new"

    resources :password_resets

    resources :mailing_lists do
      get :confirm
      get :confirm_private_reply
      resources :posts
    end

    resources :posts

    get '/people/:person_id/results' => 'results#person', constraints: { person_id: /\d+/ }
    get '/people/:person_id/:year' => 'results#person', constraints: { person_id: /\d+/, year: /\d\d\d\d/ }, as: :person_results_year
    get '/people/:person_id' => 'results#person', constraints: { person_id: /\d+/ }
    get '/people/list' => 'people#list'
    get '/people/new_login' => 'people#new_login'
    get '/people/:id/new_login' => 'people#new_login'
    get "/people/:id/account" => redirect("/people/%{id}/edit"), constraints: { person_id: /\d+/ }, as: :account_person
    get "/people/:id/editors/:editor_id/create" => "editors#create", constraints: { id: /\d+/, editor_id: /\d+/ }, as: :create_person_editor
    get "/people/:id/editors/:editor_id/destroy" => "editors#destroy", constraints: { id: /\d+/, editor_id: /\d+/ }, as: :destroy_person_editor
    get "/people/:id/editor_requests/:editor_id/create" => "editor_requests#create", constraints: { id: /\d+/, editor_id: /\d+/ }, as: :create_person_editor_request
    get "/people/:id/editor_requests/:editor_id/destroy" => "editor_requests#destroy", constraints: { id: /\d+/, editor_id: /\d+/ }, as: :destroy_person_editor_request

    resources :people do
      post :create_login, on: :collection
      resources :editors
      resources :editor_requests
      resources :events
      resource :membership
      resources :orders
      resources :results
      resources :versions
      collection do
        get :account
      end
    end

    resources :racing_associations
    get '/results/:year/:discipline' => 'results#index', constraints: { year: /(19|20)\d\d/ }, as: :results_year_discipline
    get '/results/:year' => 'results#index', constraints: { year: /(19|20)\d\d/ }, as: :results_year
    get '/results/:discipline' => 'results#index'
    resources :results do
      member do
        patch :update_attribute
      end
    end
    get '/schedule/:year/calendar' => 'schedule#index', constraints: { year: /\d\d\d\d/ }
    get '/schedule/:year/calendar' => 'schedule#calendar', constraints: { year: /\d\d\d\d/ }
    get '/schedule/calendar.xls' => redirect("/calendar.xls")
    get '/schedule/calendar.ics' => redirect("/calendar.ics")
    get '/schedule/calendar.atom' => redirect("/calendar.atom")
    get '/schedule/calendar' => 'schedule#calendar'
    get '/schedule/list/:discipline' => 'schedule#list'
    get '/schedule/:year/list/:discipline' => 'schedule#list', constraints: { year: /\d\d\d\d/ }
    get '/schedule/:year/list' => 'schedule#list', constraints: { year: /\d\d\d\d/ }
    get '/schedule/:year(/:discipline)' => 'schedule#index', constraints: { year: /\d\d\d\d/ }, as: :schedule_index
    get '/schedule/:year' => 'schedule#index', constraints: { year: /\d\d\d\d/ }
    get '/schedule/list' => 'schedule#list'
    get '/schedule/:discipline' => 'schedule#index', constraints: { discipline: /[^\d]+/ }
    get '/sanctioning_organization/:sanctioning_organization/schedule' => 'schedule#index', as: "schedule_sanctioning_organization"
    get '/schedule' => 'schedule#index', as: :schedule

    get '/region/:region(/:year)/schedule' => 'schedule#index', as: "schedule_region", constraints: { year: /\d\d\d\d/ }
    resources :single_day_events
    get '/teams/:team_id/results' => 'results#team'
    get '/teams/:team_id/:year' => 'results#team', constraints: { person_id: /\d+/, year: /\d\d\d\d/ }, as: :team_results_year
    get '/teams/:team_id' => 'results#team'
    resources :teams do
      resources :results
    end
    resource :person_session
    get '/unauthorized' => 'person_sessions#unauthorized', as: :unauthorized
    get '/logout' => 'person_sessions#destroy', as: :logout
    get '/login' => 'person_sessions#new', as: :login
    get '/account/logout' => 'person_sessions#destroy'
    get '/account/login' => 'person_sessions#new'
    get '/account' => 'people#account', as: :account

app/models/events/children.rb
module Events
  module Children
    extend ActiveSupport::Concern

    included do
      validate :parent_is_not_self

      belongs_to :parent, foreign_key: "parent_id", class_name: "Event"
      has_many :children,
               -> { order :date },
               class_name: "Event",
               foreign_key: "parent_id",
               dependent: :destroy,
               after_add: :children_changed,
               after_remove: :children_changed

      scope :child, lambda { where("parent_id is not null") }
      # :root?
      scope :not_child, lambda { where("parent_id is null") }

      scope :not_single_day_event, lambda {
        where "type is null or type != 'SingleDayEvent'"
      }
    end

    # Update child events from parents' attributes if child attribute has the
    # same value as the parent before update
    def update_children
      return true if new_record? || children.count == 0

      changes_for_propogation.each { |change| update_child_attribute(change) }
      children.each(&:update_children)

      true
    end

    def changes_for_propogation
      changes.select { |key, value| propogated_attributes.include?(key) }
    end

    def update_child_attribute(change)
      attribute = change.first
      was = change.last.first
      if was.blank?
        SingleDayEvent.where(
          "(#{attribute}=? or #{attribute} is null or #{attribute} = '') and parent_id=?", was, self[:id]
        ).update_all(attribute => self[attribute])
      else
        SingleDayEvent.where(attribute => was, parent_id: id).update_all(attribute => self[attribute])
      end
    end

    # Synch Races with children. More accurately: create a new Race on each child Event for each Race on the parent.
    def propagate_races
      # Do nothing in superclass
    end

    def children_changed(child)
      # Don't trigger callbacks
      Event.where(id: id).update_all(updated_at: Time.zone.now)
      true
    end

    # Always return false
    def missing_parent?
      false
    end

    def missing_children?
      missing_children.any?
    end

    # Always return empty Array
    def missing_children
      []
    end

    def multi_day_event_children_with_no_parent?
      multi_day_event_children_with_no_parent.any?
    end

    def multi_day_event_children_with_no_parent
      return [] unless name && date

      @multi_day_event_children_with_no_parent ||= SingleDayEvent.where(
          "parent_id is null and name = ? and extract(year from date) = ?
           and ((select count(*) from events where name = ? and extract(year from date) = ? and type in ('MultiDayEvent', 'Series', 'WeeklySeries')) = 0)",
           self.name, self.date.year, self.name, self.date.year)
      # Could do this in SQL
      if @multi_day_event_children_with_no_parent.size == 1
        @multi_day_event_children_with_no_parent = []
      end
      @multi_day_event_children_with_no_parent
    end

    def missing_parent
      nil
    end

    def parent_is_not_self
      if parent_id && parent_id == id
        errors.add("parent", "Event cannot be its own parent")
      end
    end

    def root_id
      root.try :id
    end
  end
end

app/models/events/comparison.rb
module Events
  module Comparison
    extend ActiveSupport::Concern

    include Comparable

    def ==(other)
      if self.equal?(other)
        return true
      end

      if !other.respond_to?(:id) || !other.respond_to?(:new_record?)
        return false
      end

      if new_record? || other.new_record?
        return false
      end

      id == other.id
    end

    def eql?(other)
      if self.equal?(other)
        return true
      end

      if !other.respond_to?(:id) || !other.respond_to?(:new_record?)
        return false
      end

      if new_record? || other.new_record?
        return false
      end

      id == other.id
    end

    def <=>(other)
      return -1 if other.nil? || !other

      if date
        if other.date
          return date <=> other.date
        else
          return -1
        end
      elsif other.date
        return 1
      end

      unless new_record? || other.new_record?
        return id <=> other.id
      end

      0
    end
  end
end

app/controllers/events_controller.rb
# Longer-term, this controller should handle the schedule
class EventsController < ApplicationController
  def index
    respond_to do |format|
      format.html {
        if params[:person_id]
          @person = Person.find(params[:person_id])
          @events = Event.editable_by(@person).current_year_and_later
        else
          redirect_to schedule_path
        end
      }
      format.json { render json: events_for_api(params[:year]) }
      format.xml { render xml: events_for_api(params[:year]).to_xml }
    end
  end

  private

  def events_for_api(year)
    if year.blank?
      year = RacingAssociation.current.effective_year
    end
    Event.year year.to_i
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
  LONG_DAYS_OF_WEEK = %w{ Sunday Monday Tuesday Wednesday Thursday Friday Saturday } unless defined?(LONG_DAYS_OF_WEEK)

  # Sunday, Monday, …
  def long_day_of_week(index)
    LONG_DAYS_OF_WEEK[index]
  end

  # Show link even if not approved because this is for admins
  def link_to_flyer(event)
    return unless event

    if event.flyer.blank?
      event.full_name
    else
      link_to(event.full_name, event.flyer).html_safe
    end
  end

  # Build links like Cascade Classic: Mt. Bachelor Stage
  def link_to_parents(event)
    html = ""
    event.ancestors.reverse.each do |e|
      if e.parent
        html << link_to(truncate(e.name, length: 40), edit_admin_event_path(e), class: "obvious")
        html << ": "
      else
        html << link_to(truncate(e.name, length: 40), edit_admin_event_path(e), class: "obvious")
        html << " (#{e.friendly_class_name}): "
      end
    end
    html.html_safe
  end

  # Choose POST or PATCH. Not sure why we need this.
  def form_method_for(event)
    if event.new_record?
      :post
    else
      :patch
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  # Display email link to promoter. Uses event email if there is one.
  # Displays promoter email in promoter's name is blank.
  # Displays just promoter's name if there are no email addresses.
  def link_to_event_email(event)
    email = event_email(event)

    name = event.promoter.name if event.promoter && event.promoter.name.present?
    name = email if name.nil?

    if email.present?
      mail_to email, name
    else
      name
    end
  end

  def event_email(event)
    email = event.email if event.email.present?
    email = event.promoter.email if !email && event.promoter && event.promoter.email.present?
    email
  end

  # FIXME Move to Event?
  # TODO rename to event_phone
  def link_to_event_phone(event)
    return event.phone if event.phone.present?
    event.promoter.home_phone if event.promoter && event.promoter.home_phone.present?
  end

  # FIXME move to event?
  # Only show link if flyer approved
  def public_link_to_flyer(event, text = nil)
    return unless event && event.respond_to?(:flyer)
    if event.flyer_approved?
      link_to_flyer event, text
    elsif text.present?
      text
    else
      event.full_name
    end
  end

  def short_human_date_range(event)
    if event.is_a?(MultiDayEvent)
      event.date_range_s
    else
      event.date.to_s(:short_with_week_day)
    end
  end

  # Show link even if not approved
  def link_to_flyer(event, text = nil)
    return unless event

    text = text || event.full_name

    if event.flyer.blank?
      text
    else
      link_to(text, event.flyer).html_safe
    end
  end

  def notes_class(event)
    if event.notes.count("\n") > 2
      "event_notes large"
    else
      "event_notes"
    end
  end
end

app/views/admin/events/_events.html.erb
<h3 class="events">Events</h3>

<table class="base table table-striped">
  <thead>
    <tr>
      <th colspan="3" class="actions">
        <% if @event.any_results_including_children? %>
        <%= link_to event_results_path(@event),
              class: "icon",
              title: 'View public results web page' do %>
            <span class="glyphicon glyphicon-list"></span>
          <% end %>
        <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
    <%- if @event.new_record? %>
    <tr>
      <td colspan="3">Save new event to add child events.</td>
    </tr>
    <%- end %>
  <%- @event.children.sort.each do |single_day_event| -%>
    <tr id="event_<%= single_day_event.id %>_row">
      <td class='nowrap'><%= link_to single_day_event.date.strftime('%A, %B %-d'), edit_admin_event_path(single_day_event) %></td>
      <td class='link'><%= link_to single_day_event.name, edit_admin_event_path(single_day_event) %></td>
      <td class="actions">
        <% if administrator? %>
          <%= link_to(
                admin_event_path(single_day_event),
                remote: true,
                class: "icon",
                id: "destroy_event_#{single_day_event.id}",
                title: "Delete event",
                method: :delete) do %>
            <span class="glyphicon glyphicon-minus-sign"></span>
          <% end %>
        <% end %>
      </td>
    </tr>
    <%- end -%>
    <tr>
      <td class='nowrap'>
        <% if @event.children.empty? && administrator? && !@event.new_record? -%>
        <span class="weak">No events. Click [+] button to add a new child event.</span>
        <% end -%>
      </td>
      <td class='link'></td>
      <td class="actions">
        <% if administrator? && !@event.new_record?  %>
          <%= link_to(
            new_admin_event_path(event: { parent_id: @event.id, type: @event.is_a?(MultiDayEvent) ? "SingleDayEvent" : "Event" }),
            class: "icon",
            title: "Add child event",
            id: "new_event"
          ) do %>
            <span class="glyphicon glyphicon-plus-sign"></span>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/admin/events/_nav.html.erb
<% nav_caption = %Q{
  <div>#{link_to(event.name, edit_admin_event_path(event)) unless event.new_record?}</div>
  <div class="right">
  #{link_to(image_tag('/images/icons/web_page.png', :title => 'View public results web page', :alt => 'View public results web page'), 
     {:controller => '/results', :action => 'event', :year => event.date.year, 
     :discipline => event.discipline, :id => event.id},
     { :class => "image" }) unless event.standings.empty?}  
  </div>
} %>
<% table :caption => nav_caption, :class => "event_nav clear span-3", :insert_header => true, :columns => 2 do %>
  <% event.standings.each do |standings| -%>
  <tr id="standings_<%= standings.id %>_row">
    <td class="standings"><%= link_to standings.name, edit_admin_standings_path(standings) %></td>
    <td>
      <%= link_to_remote image_tag('/images/buttons/small_remove_solo.gif'),
      :url => admin_standings_url(standings),
      :html => { :class => "image", :id => "destroy_standings_#{standings.id}" },
      :confirm => "Really delete #{standings.name}?",
      :complete => evaluate_remote_response, 
      :method => :delete
      %>
    </td>
  </tr>
  <% if defined?(race) && !race.nil?
       races = [race]
     else
       races = standings.races
     end
  races.each do |race| %>
  <tr id="race_<%= race.id %>_row">
    <td class="race">
      <%= link_to race.name, edit_admin_race_path(race) %>
      <%= "&nbsp;&nbsp;(#{race[:field_size]})" if race[:field_size] %>
    </td>
    <td>
      <%= link_to_remote image_tag('/images/buttons/small_remove_solo.gif'),
      :url => admin_race_url(race),
      :html => { :class => "image", :id => "destroy_race_#{race.id}" },
      :complete => evaluate_remote_response, 
      :method => :delete
      %>
    </td>
  </tr>
  <% end %>
  <% end %>
  <% if event.standings.empty? %>
  <tr>
    <td colspan="2" class="empty">No results</td>
  </tr>
  <% end %>
  <% unless event.new_record? -%>
  <tr>
    <td colspan="4">
      <div class="page_buttons">
        <%= label_tag :results_file, "Import Results", :class => "left", :id => "upload_form_label" %>
        <% form_tag upload_admin_event_path(event), :multipart => true, :id => "upload_form", :style => "clear" do %>
          <div>
            <%= file_field_tag "results_file", 
              :style => "width: 250px;", 
              :onchange => "$('upload_form_label').hide(); $('upload_form').hide(); $('upload_progress').show(); $('upload_form').submit();" %>
          </div>
        <% end -%>
        <div id="upload_progress" style="display: none;"><em>Importing Results</em>&nbsp;<%= image_tag "icons/spinner.gif" %></div>
      </div>
    </td>
  </tr>
  <% end -%>
<% end -%>

app/views/admin/events/_parent.html.erb
<% if administrator? && !@event.new_record? -%>
  <%- if @event.missing_parent? -%>
    <p>
    This event has no parent.
    <%= link_to"Set it to the #{@event.missing_parent.friendly_class_name} #{@event.missing_parent.name}",
      {action: 'set_parent', parent_id: @event.missing_parent.id, child_id: @event.id},
      class: 'obvious', id: 'set_parent' %>.
    </p>

  <%- elsif @event.missing_children? -%>
    <p>
    There are <%= pluralize(@event.missing_children.size, 'event') %> named <%= @event.name %> that aren't children of this
    <%= @event.friendly_class_name %>.
    <%= link_to "Add #{pluralize(@event.missing_children.size, 'child')}",
      {action: 'add_children', parent_id: @event.id,},
      class: 'obvious' %>.
    </p>
  <%- end -%>

  <%- if @event.multi_day_event_children_with_no_parent? -%>
    <p>
    Found <%= pluralize(@event.multi_day_event_children_with_no_parent.size, 'event') %> named <%= @event.name %>.
    <%= link_to "Make a parent #{MultiDayEvent.guess_type(@event.multi_day_event_children_with_no_parent).friendly_class_name}",
      {action: 'create_from_children', id: @event.id},
      class: 'obvious' %>.
    </p>
  <%- end -%>
<%- end -%>

app/views/admin/events/destroy.js.erb
jQuery('#event_<%= @event.id %>_row').effect('puff', {}, 2000);
jQuery.hide('#warn');
jQuery.show('#notice');
jQuery('notice_span').html('Deleted <%= @event.name %>');

app/views/admin/events/destroy_races.js.erb
<% @races.each do |race| %>
  jQuery('#race_<%= race.id %>_row').effect('puff', {}, 200);
<% end %>

<% if @combined_results %>
  jQuery('#event_<%= @combined_results.id %>_row').effect('puff', {}, 200);
<% end %>

jQuery('#update_races_progress').fadeOut(100);
jQuery("#warn").hide();
jQuery('#notice').show();

jQuery('#notice_span').html('Deleted races');

app/views/admin/events/first_aid.html.erb
<% @page_title = 'First Aid' %>

<% form_tag({}, { :method => :get }) do %>
  <%= check_box_tag "past_events", "true", @past_events, :onclick => "form.submit();" %>&nbsp;Show past events
<% end -%>

<%= table :events, "#{Date.today.year} First Aid" do |t|
  t.column :first_aid_provider, :title => "Provider", :editable => true
  t.column :date, :format => :short_with_week_day
  t.column :name, :link => true
  t.column :city_state, :title => "Location"
end -%>

<div>
  <%= link_to 'Email', :action => 'first_aid_provider_email' %>
</div>

app/views/admin/events/index.html.erb
<% @page_title = "Admin: Schedule: #{@year}" %>

<%= render "shared/years", year: @year, discipline: nil %>
<%= render "shared/months" %>

<div class="row form-group">
  <div class="col-sm-12">
    <%= link_to 'New Event', new_admin_event_path(event: { date: Time.zone.local(@year).to_date.to_s(:db) }), {class: "btn btn-default", id: "new_event"} %>
  </div>
</div>

<%- @schedule.months.each do |month| -%>
<div class="row">
  <div class="col-sm-12">
    <h3 class="month"><a id='<%= month.name.downcase %>'><%= month.name %> <%= @year %></a></h3>
    <table class="calendar table">
      <thead>
        <tr>
          <th>Sunday</th>
          <th>Monday</th>
          <th>Tuesday</th>
          <th>Wednesday</th>
          <th>Thursday</th>
          <th>Friday</th>
          <th>Saturday</th>
        </tr>
      </thead>
      <tbody>
        <%- month.weeks.each do |week| -%>
        <tr class="month">
          <%- week.days.each do |day| -%>
            <%- if day.other_month? -%>
          <td class="day_from_other_month"><div class="number"><%= day.day_of_month -%></div>
            <%- else -%>
          <td class="day">
            <div class="number"><%= day.day_of_month -%></div>
              <%- day.events.each do |event| -%>
            <div class="event"><%= link_to event.full_name, edit_admin_event_path(event) %></div>
              <%- end -%>
            <%- end -%>
          </td>
          <%- end -%>
        </tr>
        <%- end -%>
      </tbody>
    </table>
  </div>
</div>
<% end -%>

<% if @competitions.present? %>
<div class="row">
  <div class="col-sm-12">
    <h3>Competitions</h3>
    <% @competitions.sort_by(&:name).each do |competition| -%>
      <%= link_to competition.name, edit_admin_event_path(competition) %><br />
    <% end -%>
  </div>
</div>
<% end %>

<hr/>

<div class="row">
  <div class="col-sm-12 import_schedule">
  <%= form_tag upload_schedule_admin_events_path, multipart: true, class: "form-horizontal", id: "upload_form" do %>
    <label for="schedule_file">Import Schedule</label>
    <%= file_field_tag "schedule_file", onchange: "$('#upload_form').submit();" %>
  <% end %>
  </div>
</div>