config/routes.rb
Rails.application.routes.draw do
  scope "(:mobile)", mobile: /m/ do
    namespace :admin do
      resources :articles
      resources :article_categories
      resources :categories do
        collection do
          post :add_child
          post :recompute_bar
          post :recompute_team_bar
        end
      end

      resources :events do
        collection do
          get  :add_children
          get  :set_parent
          post :upload_schedule
        end
        member do
          get     :create_from_children
          delete  :destroy_races
          patch   :update_attribute
          post    :upload
        end
        resources :races do
          collection do
            post :propagate
          end
        end
        resource :races_collection
      end

      resources :first_aid_providers
      resources :mailing_lists do
        resources :posts do
          collection do
            post :receive
          end
        end
      end
      resources :multi_day_events
      resources :pages do
        member do
          patch :update_attribute
        end
      end
      namespace :pages do
        resources :versions do
          member do
            get :revert
          end
        end
      end
      resources :people do
        resources :aliases
        collection do
          get  :cards
          get  :duplicates
          post :import
          get  :no_cards
          post :number_year_changed
          post :preview_import
          post :resolve_duplicates
        end
        member do
          get    :card
          post   :toggle_member
        end
        resources :race_numbers
        resources :results do
          post :move
        end
        resources :scores
      end
      post "/people/:id/merge/:other_person_id" => "people#merge", constraints: { id: /\d+/, other_person_id: /\d+/ }, as: :merge_person

      resources :races do
        member do
          patch :update_attribute
        end
        resources :results
      end

      resources :race_numbers

      resources :results do
        collection do
          post :find_person
          post :results
        end
        member do
          patch :update_attribute
        end
        resources :races
      end

      resources :series
      resources :single_day_events

      resources :teams do
        resources :aliases
        member do
          post  :cancel_in_place_edit
          post  :destroy_name
          post  :toggle_member
          patch :update_attribute
        end
      end
      post "/teams/:id/merge/:other_team_id" => "teams#merge", constraints: { id: /\d+/, other_team_id: /\d+/ }, as: :merge_team

      resources :velodromes do
        member do
          patch :update_attribute
        end
      end
      resources :weekly_series
    end

    resources :articles
    resources :article_categories
    resources :categories do
      resources :races
    end

    get ':controller/:id/aliases/:alias_id/destroy' => :destroy_alias, constraints: { id: /\d+/ }

    get '/admin/results/:id/scores' => 'admin/results#scores'
    get '/admin/racers' => 'admin/racers#index'
    patch '/admin/persons/update_attribute/:id' => 'admin/people#update_attribute'
    get '/admin' => 'admin/home#index', as: :admin_home

    get '/bar' => 'competitions/bar#index', as: "bar_root"
    get "/bar/:year/:discipline/:category" => "competitions/bar#show", as: "bar_full"
    get "/bar(/:year(/:discipline(/:category)))" => "competitions/bar#show", as: "bar", defaults: { discipline: "overall", category: "senior_men" }

    get '/cat4_womens_race_series/:year' => 'competitions/competitions#show', as: :cat4_womens_race_series, type: 'cat4_womens_race_series', constraints: { year: /\d{4}/ }
    get '/cat4_womens_race_series' => 'competitions/competitions#show', type: 'cat4_womens_race_series'

    resources :duplicate_people

    get '/events/:event_id/results' => 'results#event'
    get '/events/:event_id/people/:person_id/results' => 'results#person_event'
    get '/events/:event_id/teams/:team_id/results' => 'results#team_event'
    get '/events/:event_id/teams/:team_id/results/:race_id' => 'results#team_event'
    get '/events/:event_id' => 'results#event'

    resources :event_teams do
      resources :event_team_memberships
    end

    resources :events do
      resources :event_team_memberships
      resources :event_teams
      resources :results
      resources :people do
        resources :results
        resources :event_team_memberships
      end
      resources :races
      resources :teams do
        resources :results
      end
    end

    resources :event_team_memberships

    get "/human_dates/:date" => "human_dates#show", constraints: { date: /.*/ }

    resources :photos

    resources :races
    get '/rider_rankings/:year' => 'competitions/competitions#show', as: :rider_rankings, type: 'rider_rankings', constraints: { year: /\d{4}/ }
    get '/rider_rankings' => 'competitions/competitions#show', as: :rider_rankings_root, type: 'rider_rankings'
    get '/ironman(/:year)' => 'competitions/ironman#index', as: :ironman
    get '/oregon_cup/rules' => 'competitions/oregon_cup#rules'
    get '/oregon_cup/races' => 'competitions/oregon_cup#races'
    get '/oregon_cup/:year' => 'competitions/oregon_cup#index', as: :oregon_cup
    get '/oregon_cup' => 'competitions/oregon_cup#index', as: :oregon_cup_root
    get "/oregon_tt_cup/:year" => "competitions/competitions#show", type: "oregon_tt_cup"
    get "/oregon_tt_cup" => "competitions/competitions#show", type: "oregon_tt_cup"
    get '/oregon_womens_prestige_series' => "competitions/competitions#show", type: "oregon_womens_prestige_series"
    get '/owps' => "competitions/competitions#show", type: "oregon_womens_prestige_series"
    get "/:slug/join" => "event_team_memberships#new"

    resources :password_resets

    resources :mailing_lists do
      get :confirm
      get :confirm_private_reply
      resources :posts
    end

    resources :posts

    get '/people/:person_id/results' => 'results#person', constraints: { person_id: /\d+/ }
    get '/people/:person_id/:year' => 'results#person', constraints: { person_id: /\d+/, year: /\d\d\d\d/ }, as: :person_results_year
    get '/people/:person_id' => 'results#person', constraints: { person_id: /\d+/ }
    get '/people/list' => 'people#list'
    get '/people/new_login' => 'people#new_login'
    get '/people/:id/new_login' => 'people#new_login'
    get "/people/:id/account" => redirect("/people/%{id}/edit"), constraints: { person_id: /\d+/ }, as: :account_person
    get "/people/:id/editors/:editor_id/create" => "editors#create", constraints: { id: /\d+/, editor_id: /\d+/ }, as: :create_person_editor
    get "/people/:id/editors/:editor_id/destroy" => "editors#destroy", constraints: { id: /\d+/, editor_id: /\d+/ }, as: :destroy_person_editor
    get "/people/:id/editor_requests/:editor_id/create" => "editor_requests#create", constraints: { id: /\d+/, editor_id: /\d+/ }, as: :create_person_editor_request
    get "/people/:id/editor_requests/:editor_id/destroy" => "editor_requests#destroy", constraints: { id: /\d+/, editor_id: /\d+/ }, as: :destroy_person_editor_request

    resources :people do
      post :create_login, on: :collection
      resources :editors
      resources :editor_requests
      resources :events
      resource :membership
      resources :orders
      resources :results
      resources :versions
      collection do
        get :account
      end
    end

    resources :racing_associations
    get '/results/:year/:discipline' => 'results#index', constraints: { year: /(19|20)\d\d/ }, as: :results_year_discipline
    get '/results/:year' => 'results#index', constraints: { year: /(19|20)\d\d/ }, as: :results_year
    get '/results/:discipline' => 'results#index'
    resources :results do
      member do
        patch :update_attribute
      end
    end
    get '/schedule/:year/calendar' => 'schedule#index', constraints: { year: /\d\d\d\d/ }
    get '/schedule/:year/calendar' => 'schedule#calendar', constraints: { year: /\d\d\d\d/ }
    get '/schedule/calendar.xls' => redirect("/calendar.xls")
    get '/schedule/calendar.ics' => redirect("/calendar.ics")
    get '/schedule/calendar.atom' => redirect("/calendar.atom")
    get '/schedule/calendar' => 'schedule#calendar'
    get '/schedule/list/:discipline' => 'schedule#list'
    get '/schedule/:year/list/:discipline' => 'schedule#list', constraints: { year: /\d\d\d\d/ }
    get '/schedule/:year/list' => 'schedule#list', constraints: { year: /\d\d\d\d/ }
    get '/schedule/:year(/:discipline)' => 'schedule#index', constraints: { year: /\d\d\d\d/ }, as: :schedule_index
    get '/schedule/:year' => 'schedule#index', constraints: { year: /\d\d\d\d/ }
    get '/schedule/list' => 'schedule#list'
    get '/schedule/:discipline' => 'schedule#index', constraints: { discipline: /[^\d]+/ }
    get '/sanctioning_organization/:sanctioning_organization/schedule' => 'schedule#index', as: "schedule_sanctioning_organization"
    get '/schedule' => 'schedule#index', as: :schedule

    get '/region/:region(/:year)/schedule' => 'schedule#index', as: "schedule_region", constraints: { year: /\d\d\d\d/ }
    resources :single_day_events
    get '/teams/:team_id/results' => 'results#team'
    get '/teams/:team_id/:year' => 'results#team', constraints: { person_id: /\d+/, year: /\d\d\d\d/ }, as: :team_results_year
    get '/teams/:team_id' => 'results#team'
    resources :teams do
      resources :results
    end
    resource :person_session
    get '/unauthorized' => 'person_sessions#unauthorized', as: :unauthorized
    get '/logout' => 'person_sessions#destroy', as: :logout
    get '/login' => 'person_sessions#new', as: :login
    get '/account/logout' => 'person_sessions#destroy'
    get '/account/login' => 'person_sessions#new'
    get '/account' => 'people#account', as: :account

app/models/home.rb
class Home < ActiveRecord::Base
  belongs_to :photo

  def self.current
    Home.first || Home.create!
  end
end

app/controllers/admin/home_controller.rb
module Admin
  # Just redirect to admin events index
  class HomeController < Admin::AdminController
    def index
      flash.keep
      redirect_to admin_events_path
    end
  end
end

app/controllers/home_controller.rb
# Homepage
class HomeController < ApplicationController
  before_action :require_administrator, except: [ :index, :show ]

  # Show homepage
  # === Assigns
  # * upcoming_events
  # * recent_results: Events with Results within last two weeks
  def index
    @page_title = RacingAssociation.current.name

    assign_home
    @photo = @home.photo
    @posts = recent_posts

    @events_with_recent_results = Event.with_recent_results(@home.weeks_of_recent_results.weeks.ago)
    @most_recent_event_with_recent_result = Event.most_recent_with_recent_result(@home.weeks_of_recent_results.weeks.ago)

    @news_category = ArticleCategory.where(name: "news")
    if @news_category
      @recent_news = Article.recent_news(@home.weeks_of_upcoming_events.weeks.ago, @news_category)
    end

    respond_to do |format|
      format.html { render_page }
    end
  end

  def edit
    assign_home
  end

  def update
    assign_home
    if @home.update(home_params)
      expire_cache
      redirect_to edit_home_path
    else
      render :edit
    end
  end

  def show
    return redirect_to(root_path)
  end

  private

  def assign_home
    @home = Home.current
  end

  def home_params
    params_without_mobile.require(:home).permit(:photo_id, :weeks_of_recent_results, :weeks_of_upcoming_events)
  end

  def recent_posts
    Post.recent
  end
end

app/helpers/home_helper.rb
module HomeHelper
  # Set homepage @photo_columns to 1..3 based of homepage photo size
  def photo_width_x_height(width, height)
    @photo_width = width
    @photo_height = height
    case @photo_width
    when 0..285
      @photo_columns = 1
    when 286..574
      @photo_columns = 2
    else
      @photo_columns = 3
    end
  end
end

app/views/home/_most_recent_event_with_recent_result.html.erb
<% if event %>
<h3><%= link_to event.full_name, event_results_path(event) %> Winners</h3>
<table class="base table table-striped">
  <thead/>
  <tbody>
    <% event.races_with_results.sort_by(&:name)[0, 12].each do |race| %>
  <tr>
    <td><%= link_to race.name, event_results_path(event, anchor: "race_#{race.id}") %></td>
    <td><%= link_to race.results.sort.first.name, person_results_path(race.results.sort.first.person_id) %></td>
  </tr>
  <% end %>
  <tr>
    <td colspan="2"><%= link_to("More &hellip;".html_safe, schedule_path) %></td>
  </tr>
  </tbody>
</table>
<% end %>

app/views/home/_photo.html.erb
<% if photo.link.present? %>
<%= link_to photo.link do %>
  <%= image_tag photo.image.desktop.url, title: photo.title, class: "hero-photo img-responsive center-block" %>
<% end %>
<% else %>
<%= image_tag photo.image.desktop.url, title: photo.title, class: "hero-photo img-responsive center-block" %>
<% end %>

<% if photo.caption.present? %>
<span class="hero-photo-caption"><%= markdown photo.caption %></span>
<% end %>

app/views/home/_photo_row.html.erb
<% if photo %>
<div class="row">
  <% if photo.widescreen? %>
    <div class="col-sm-12">
      <%= render "home/photo", photo: photo %>
    </div>
    <% elsif photo.portrait? %>
    <div class="col-sm-6">
      <%= render "home/photo", photo: photo %>
    </div>
    <div class="col-sm-6">
      <%= render "most_recent_event_with_recent_result", event: most_recent_event_with_recent_result.first %>
    </div>
    <% else %>
    <div class="col-sm-8">
      <%= render "home/photo", photo: photo %>
    </div>
    <div class="col-sm-4">
      <%= render "most_recent_event_with_recent_result", event: most_recent_event_with_recent_result.first %>
    </div>
  <% end %>
</div>
<% end %>

app/views/home/_post.html.erb
<tr>
  <td><%= link_to post.subject, post_path(post) %></td>
  <td class="mailing_list hidden-xs"><%= link_to post.mailing_list.friendly_name, mailing_list_posts_path(post.mailing_list) %></td>
  <td class="from hidden-xs"><%= post.last_reply_from_name || post.from_name %></td>
</tr>

app/views/home/_posts.html.erb
<% if posts.present? %>
<div class="row">
  <div class="col-sm-12">
    <h3><%= link_to "Posts", mailing_lists_path %></h3>
    <%= table class: "mailing_lists", columns: 1 do %>
    <tbody>
      <%= render partial: "home/post", collection: posts %>
    </tbody>
    <% end %>
  </div>
</div>
<% end %>

app/views/home/_recent_results.html.erb
<h3><%= link_to 'Results', results_path %></h3>
<%= table id: "home_page_results", columns: 2 do %>
  <%- events_with_recent_results.sort_by(&:date).reverse[0, mobile_request? ? 6 : 1000].each do |event| -%>
  <tr>
    <td class="date"><%= link_to event.date.to_s(:md), event_results_path(event) %></td>
    <td class="event"><%= link_to event.full_name, event_results_path(event) %></td>
  </tr>
  <%- end -%>
  <%- if events_with_recent_results.empty? -%>
  <tr>
    <td colspan="2">No results in the last <%= weeks_of_recent_results %> weeks</td>
  </tr>
  <%- end -%>
  <tr>
    <td colspan="2"><%= link_to("More &hellip;".html_safe, results_path) %></td>
  </tr>
<% end -%>

app/views/home/_upcoming_events.html.erb
<h3><%= link_to "Schedule", schedule_path %></h3>
<%= table id: "upcoming_events", columns: 4 do %>
  <% Event.upcoming(weeks_of_upcoming_events).sort_by(&:date)[0, mobile_request? ? 6 : 1000].each do |event| %>
    <tr>
      <td class="date"><%= public_link_to_flyer(event, event.date.to_s(:short_with_week_day)) %></td>

      <% unless mobile_request? %>
      <td class="beginner_friendly icon">
        <% if event.beginner_friendly? %>
          <%= link_to("http://www.obra.org/beginner_friendly.html",
                      class: "beginner_friendly", title: "Beginner friendly event") do %>
            <span class="glyphicon glyphicon-ok-circle"></span>
          <% end %>
        <% end %>
      </td>
      <% end %>

      <td class="event"><%= public_link_to_flyer(event) %></td>

      <% unless mobile_request? %>
      <td class="discipline">
        <%= link_to event.discipline,
            schedule_index_path(
              year: RacingAssociation.current.effective_year,
              discipline: Discipline[event.discipline].to_param,
              anchor: event.date.strftime("%B").downcase
            ) %>
      </td>
      <% end %>

    </tr>
  <% end %>
  <tr>
    <td colspan="4">
      <% if mobile_request? %>
      <%= link_to("More &hellip;".html_safe, schedule_list_path) %>
      <% else %>
      <%= link_to("More &hellip;".html_safe, schedule_path) %>
      <% end %>
    </td>
  </tr>
<% end -%>

app/views/home/edit.html.erb
<% @show_tabs = true %>
<%= render "shared/errors", object: @home %>

<h2>Home</h2>

<%= form_for @home, url: home_path, html: { class: "form-horizontal", role: "form" } do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.labelled_select :photo_id,
            Photo.order("updated_at desc").map { |photo| [ photo.caption, photo.id ] },
            include_blank: true
      %>
      <div class="form-group">
        <label class="col-sm-4 control-label"></label>
        <div class="col-sm-8">
          <%= link_to "Edit photos", photos_path, class: "obvious" %>
        </div>
      </div>
      <%= f.labelled_text_field :weeks_of_recent_results, "Results (weeks)" %>
      <%= f.labelled_text_field :weeks_of_upcoming_events, "Upcoming (weeks)" %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <%= submit_tag "Save", class: "btn btn-default", id: "save" %>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<% cache cache_key(@today) do %>
  <div class="home">
    <%= render "photo_row",
        photo: @photo,
        most_recent_event_with_recent_result: @most_recent_event_with_recent_result,
        weeks_of_recent_results: @home.weeks_of_recent_results %>
    <div class="row">
      <div class="col-sm-6">
        <%= render_page "home/upcoming_events", weeks_of_upcoming_events: @home.weeks_of_upcoming_events %>
      </div>
      <div class="col-sm-6">
        <%= render_page "home/recent_results",
            events_with_recent_results: @events_with_recent_results,
            weeks_of_recent_results: @home.weeks_of_recent_results %>
      </div>
    </div>

    <%= render_page "home/posts", posts: @posts %>

    <%= render_page "home/ads" %>
    <%= render_page "home/links" %>
    <%= render_page "home/associated" %>
  </div>
<% end %>